Update to version 0.22
- add install script for debian-11
- remove non systemd installation files (centos6)
- add 2 new weather templates, removed all old ones

diff --git a/usr/sbin/dsbd b/usr/sbin/dsbd
--- a/usr/sbin/dsbd
+++ b/usr/sbin/dsbd
@@ -4,39 +4,36 @@
 # DSBD - Digital Signage Background Daemon
 #
 # ctime: 2015-12-18 /TR
-# mtime: 2017-07-05 /TR
+# mtime: 2022-05-10 /TR
 #############################################
 
-SMB="$1"
-WEB="$2"
-LOG="$3"
-FIFO="$4"
-CACHE="$5"
+# these settings are okay for most systems:
+SMB="/home/dsbd/$DSB_NAME"
+WEB="/var/www/html/dsbd/$DSB_NAME"
+LOG="/var/log/dsbd/$DSB_NAME.log"
+CACHE="$DSB_CACHE/$DSB_NAME.d"
+FIFO="$CACHE/$DSB_NAME.fifo"
 
 # version information
-DSB_VERSION="DSBD 0.19"
+DSB_VERSION="DSBD 0.22"
 
 # javascript files and templates
 LIBFILES="/var/lib/dsbd"
 
-# reload delay time
-# - chrome client should check for changes in the id file "if_X.html.txt"
-# - time in seconds
-DSB_RELOAD_TIME="5"
+# reload delay time (seconds)
+DSB_RELOAD_TIME="10"
 
-# dsbd will check for changes in news feeds
-# - time is in seconds
-DSB_NEWSFEED_CHECK="300"
+# dsbd will recheck for changes @ news feeds (seconds)
+DSB_NEWSFEED_CHECK="240"
+
+# ds-schedule re check time (seconds)
+DSB_SCHEDULE_CHECK="60"
+
+# ds-schedule filename
+DSB_SCHEDULE="$SMB/DS-Schedule.dsbs"
 
 # mutool quality settings for the pdf output
 PDF_QUALITY="-r 110"
-
-exec 1>>$LOG
-exec 2>&1
-
-# fifo, alles @ fd 23
-exec 23<>${FIFO}
-FIFO_FD=23
 
 # log sth.
 log() {
@@ -59,17 +56,36 @@ hashsum() {
 
 # called once in beginning
 startup() {
+
+  # ExecStartPre mode:
+  # -> running as root, init the directories and exit
+  cd /tmp
+  if [ $EUID == 0 ]; then
+    for d in "$CACHE" `dirname "$LOG"` "$SMB" "$WEB"; do
+      mkdir -p "$d"
+      chown -R $DSB_USER "$d"
+    done
+    exit 0
+  fi
+
+  # stdout, stderr and the dsbd fifo
+  exec 1>>$LOG
+  exec 2>&1
+  rm -f ${FIFO}
+  mkfifo ${FIFO}
+  exec 23<>${FIFO}
+  FIFO_FD=23
+
   log "START SERVICE ($DSB_VERSION)"
 
   # test for some tools, which are needed
   test -x /usr/bin/curl || error "Need curl!"
   test -x /usr/bin/rsync || error "Need rsync!"
-  test -x /usr/bin/ffmpeg || error "Need ffmpeg!"
   test -x /usr/bin/md5sum || error "Need md5sum!"
   test -x /usr/bin/mutool || error "Need mutool!"
   test -x /usr/bin/convert || error "Need convert!"
+  test -x /usr/bin/unoconv || error "Need unoconv / libreoffice!"
   test -x /usr/bin/dos2unix || error "Need dos2unix!"
-  test -x /usr/bin/libreoffice || error "Need libreoffice!"
 
   # register cleanup function
   trap cleanup SIGHUP SIGINT SIGTERM SIGQUIT
@@ -83,11 +99,7 @@ startup() {
 <oor:items xmlns:oor="http://openoffice.org/2001/registry" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <item oor:path="/org.openoffice.Office.Common/Filter/PDF/Export"><prop oor:name="ExportFormFields" oor:op="fuse"><value>false</value></prop></item>
 <item oor:path="/org.openoffice.Office.Common/Filter/PDF/Export"><prop oor:name="IsAddStream" oor:op="fuse"><value>false</value></prop></item>
-<item oor:path="/org.openoffice.Office.Common/Filter/PDF/Export"><prop oor:name="MaxImageResolution" oor:op="fuse"><value>300</value></prop></item>
-<item oor:path="/org.openoffice.Office.Common/Filter/PDF/Export"><prop oor:name="ReduceImageResolution" oor:op="fuse"><value>true</value></prop></item>
-<item oor:path="/org.openoffice.Office.Common/Filter/PDF/Export"><prop oor:name="UseLosslessCompression" oor:op="fuse"><value>false</value></prop></item>
-<item oor:path="/org.openoffice.Office.Common/Filter/PDF/Export"><prop oor:name="SelectPdfVersion" oor:op="fuse"><value>1</value></prop></item>
-<item oor:path="/org.openoffice.Office.Common/Filter/PDF/Export"><prop oor:name="Quality" oor:op="fuse"><value>90</value></prop></item>
+<item oor:path="/org.openoffice.Office.Common/Filter/PDF/Export"><prop oor:name="Quality" oor:op="fuse"><value>96</value></prop></item>
 EOF
 
   # Update Samba Templates (from System Templates)
@@ -97,13 +109,23 @@ EOF
     rsync -aqu "$LIBFILES/Templates/" "$SMB/Templates/"
   fi
 
-  cd $CACHE || error "Could not change to cachedir $CACHE"
+  if [ ! -f "$SMB/Standard.dsbd" ]; then
+    cat <<EOF > "$SMB/Standard.dsbd"
+[Layout]
+Left=400
+Top=300
+Resolution=0
+Type=Background
+EOF
+    unix2dos "$SMB/Standard.dsbd"
+  fi
+
+  cd "$CACHE" || error "Could not change to cachedir $CACHE"
 }
 
 # called once on end
 cleanup() {
   log "END SERVICE ($DSB_VERSION)"
-  kill $INOTIFY_PID
   exit 0
 }
 
@@ -196,6 +218,7 @@ conv_office() {
   rm -f "$File"
   # pdf nach png:
   FileNoExt=${File%.*}
+  log "conv_mutool -> $File_%03d.png $FileNoExt.pdf"
   mutool draw $PDF_QUALITY -o "$File_%03d.png" "$FileNoExt.pdf"
   rm -f "$FileNoExt.pdf"
   cd "$CACHE"
@@ -267,27 +290,27 @@ read_mediafiles() {
 }
 
 # newsfeeds
-read_newsfeed_recheck() {
+read_newsfeed_bgjob() {
   DSB_FEEDURL=`read_template_file "#Feed.txt"|head -1`
 
   # endless loop
   while :; do
-    # log "read_newsfeed_recheck id($Id) @ `date`"
+    # log "read_newsfeed_bgjob id($Id) @ `date`"
 
     # These headers should give us an unique ID:
     # 1) Last-Modified: Sat, 28 Jan 2017 08:18:28 GMT
     # 2) Content-Length: 10474
-    # - when these headers are not present, update every time...
+    # -> when these headers are not present, update every time
     ID_OLD="0"
-    test -f "$CacheDir/feed.id" && ID_OLD=`cat $CacheDir/feed.id`
+    test -f "$CacheDir/feed.id" && ID_OLD=`cat "$CacheDir/feed.id"`
     ID_NEW=`curl -s -A "$DSB_VERSION" -I "$DSB_FEEDURL" | grep -E '^(Last-Modified|Content-Length)'|hashsum 32`
     ID_EMPTY=`echo -n|hashsum 32`
     # log "FeedID new=$ID_NEW old=$ID_OLD empty=$ID_EMPTY"
     if [ "$ID_OLD" != "$ID_NEW" -o "$ID_NEW" == "$ID_EMPTY" ]; then
-      log "Updating Feed, url=$DSB_FEEDURL ..."
+      log "Updating Feed ($DSB_FEEDURL) ..."
       curl -s -A "$DSB_VERSION" "$DSB_FEEDURL" > "$CacheDir/feed.xml"
-      echo $ID_NEW > "$CacheDir/feed.id"
-      echo $ID_NEW | cut -b1-10 > "$WEB/if_$Id.html.txt"
+      echo "$ID_NEW" > "$CacheDir/feed.id"
+      echo "$ID_NEW" | cut -b1-10 > "$WEB/if_$Id.html.txt"
       ln -s -f "$CacheDir/feed.xml" "$WEB/if_$Id/feed.xml"
     fi
     sleep $DSB_NEWSFEED_CHECK
@@ -308,21 +331,30 @@ read_newsfeed() {
   # log "read_newsfeed id($Id)"
   mkdir -p "$CacheDir" "$WEB/if_$Id"
 
-  # kill old job
-  test -f "$WEB/if_$Id/feed.pid" && kill `cat "$WEB/if_$Id/feed.pid"` 2>/dev/null
+  # kill old job, when not just started within last 3 seconds
+  if [ -f "$WEB/if_$Id/feed.pid" ]; then
+    ts1=`stat -c "%Y" "$WEB/if_$Id/feed.pid"`
+    ts2=`date +%s`
+    tsDiff=$((ts2-ts1))
+    if [ $tsDiff -lt 3 ]; then
+      # log "Ignoriere NewsFeed Restart id($Id) -> tsDiff=$tsDiff"
+      return
+    fi
+    kill `cat "$WEB/if_$Id/feed.pid"` 2>/dev/null
+  fi
 
   # start new job and save id
-  read_newsfeed_recheck &
+  read_newsfeed_bgjob &
   echo $! > "$WEB/if_$Id/feed.pid"
 }
 
-# -> setzt diese Variable: $LAYOUT
+# setup $LAYOUT variable
 read_template_files() {
   LAYOUT=`read_template_file "#Layout.txt"`
   FILES=`echo "$LAYOUT" | grep -E '%\w*%' | grep -vE '(DSB_|IFRAME_)' | cut -d% -f2`
 
   # work with the "Templates"
-  # alle %xyz% platzhalter ersetzen
+  # -> replace all %xyz% templates
   for x in $FILES; do
     # Ticker und Mediafiles sind anders!
     Content=`read_template_file "#$x.txt"`
@@ -352,6 +384,8 @@ generate_iframe_ticker() {
     LAYOUT=${LAYOUT/'%DSB_TICKER%'/"$TL"}
     LAYOUT=${LAYOUT/'%DSB_TICKER_TYPED%'/"$TT"}
     LAYOUT=${LAYOUT/'%DSB_TICKER_SCROLLING%'/"$TS"}
+  else
+    LAYOUT=${LAYOUT/'%DSB_TICKER%'/" "}
   fi
 }
 
@@ -532,7 +566,8 @@ remove_layout() {
     unset TOP[$i]
     unset WIDTH[$i]
     unset HEIGHT[$i]
-    rm -rf "$WEB/$s" "$WEB/js/" "$WEB/if_$i."* "$WEB/if_$i" "$WEB/index."* "$CACHE"/*
+    rm -rf "$WEB/$s" "$WEB/js/" "$WEB/if_$i."* \
+      "$WEB/if_$i" "$WEB/index."* "$CACHE"/*
     # remove old layout, when no #keep.txt exists
     # -> disabled, currently not really useful
     # test -f "$SMB/$s/#keep.txt" || rm -rf "$SMB/$s"
@@ -545,7 +580,7 @@ remove_cached() {
   CacheDir="$CACHE/$Section"
   File=`basename "$filename"`
   hashstr=`echo "$CacheDir/$File.d/$File"|hashsum 32`
-  # log "Cache flushed: $File, hashstr:$hashstr"
+  log "Cache flushed: $File, hashstr:$hashstr"
 
   # remove old cached files
   rm -rf "$CacheDir/$File"*
@@ -562,7 +597,8 @@ handle_create() {
   # check, if current layout has changed
   if [ "$fullpath" = "$DSB_LAYOUT" ]; then
     log "Layout Reading: [$DSB_LAYOUT]"
-    cat "$DSB_LAYOUT" | dos2unix | iconv -f latin1 -t utf8 > "$CACHE/$basefile"
+    cat "$DSB_LAYOUT" | dos2unix \
+    | iconv -f latin1 -t utf8 > "$CACHE/$basefile"
     read_layout "$CACHE/$basefile"
     rm -f "$CACHE/$basefile"
   fi
@@ -598,12 +634,258 @@ handle_delete() {
   done
 }
 
-# some error checking and initializing
-test -z $5 && error "Need 5 parameter!"
+wakeup_screens_etherwake() {
+  NETDEVS=`cat /proc/net/dev | grep "eth"| cut -d: -f1`
+  for i in ${!MACS[@]}; do
+    str=${MACS[$i]}
+    str=${str#*|}
+    mac=${str:0:17}
+    for dev in ${NETDEVS[@]}; do
+      $ETHERWAKE -i "$dev" "$mac"
+      $ETHERWAKE -i "$dev" "$mac"
+    done
+  done
+}
+
+wakeup_screens_wakeonlan() {
+  # wakeonlan [-h] [-v] [-i IP_address] [-p port] [-f file] [[hardware_address] ...]
+  for i in ${!MACS[@]}; do
+    # 3=1|12:34:56:78:90:ef|DSB Lehrerzimmer
+    str=${MACS[$i]}
+    str=${str#*|}
+    mac=${str:0:17}
+    wakeonlan $mac
+    wakeonlan $mac
+  done
+}
+
+wakeup_screens_wol() {
+  for i in ${!MACS[@]}; do
+    # 3=1|12:34:56:78:90:ef|DSB Lehrerzimmer
+    str=${MACS[$i]}
+    str=${str#*|}
+    mac=${str:0:17}
+    wol $mac
+    wol $mac
+  done
+}
+
+# ON|MAC|Beschreibung
+# [Macs]
+wakeup_screens() {
+  export PATH="/sbin:/bin:/usr/sbin:/usr/bin"
+
+  # check layout link
+  old_layout=`readlink "$SMB/Layout.dsbd"`
+  if [ "x$cl_layout.dsbd" != "x$old_layout" ]; then
+    rm -f "$SMB/Layout.dsbd"
+    ln -s "$cl_layout.dsbd" "$SMB/Layout.dsbd"
+  fi
+
+  # wol via wakeonlan tool (ubuntu)
+  WOL=`which wakeonlan`
+  if [ ! -z $WOL ]; then
+    wakeup_screens_wakeonlan
+    return
+  fi
+
+  # wol via wol tool (arch linux)
+  WOL=`which wol`
+  if [ ! -z $WOL ]; then
+    wakeup_screens_wol
+    return
+  fi
+
+  # wol via ether-wake (centos)
+  WOL=`which ether-wake`
+  if [ ! -z $WOL ]; then
+    wakeup_screens_etherwake
+    return
+  fi
+
+  log "WARNING: can not find wakeonlan tool like: wol, wakeonlan, ether-wake ?!"
+}
+
+# ON|YYYYmmdd|HHMM-HHMM|Layout|Beschreibung
+function set_event() {
+  cat <<EOF > "$WEB/status.txt"
+SHUTDOWN=0
+NOTE=$cl_note
+LAYOUT=$cl_layout
+TIME=$cl_time
+DATE=$cl_date
+EOF
+  wakeup_screens
+}
+
+function set_offtime() {
+  cat <<EOF > "$WEB/status.txt"
+SHUTDOWN=1
+NOTE=$cl_note
+DATE1=$cl_date1
+DATE2=$cl_date2
+EOF
+}
+
+function set_weekplan() {
+  cat <<EOF > "$WEB/status.txt"
+SHUTDOWN=0
+NOTE=weekplan
+LAYOUT=$cl_layout
+TIME=$cl_time
+DOW=$cl_dow
+EOF
+  wakeup_screens
+}
+
+# parse schedule file -> create $WEB/status.txt
+check_schedule() {
+  local i
+  local INI="$CACHE/Schedule$$"
+
+  if [ ! -f "$DSB_SCHEDULE" ]; then
+    cat <<EOF > "$DSB_SCHEDULE"
+[Weekplan]
+[Offtimes]
+[Events]
+[Macs]
+EOF
+    unix2dos "$DSB_SCHEDULE"
+  fi
+
+  # arrays @ layout.ini
+  unset WEEKPLAN
+  unset OFFTIMES
+  unset EVENTS
+  unset MACS
+  declare -A "SECTIONS" "TYPES" "LEFT" "TOP" "WIDTH" "HEIGHT" "STYLES"
+
+  cat "$DSB_SCHEDULE" | dos2unix | iconv -f Latin1 -t utf8 > "$INI"
+  # we parse the file every minute, this could be made better, but this will be
+  # more complex, i love the KISS principle ;)  /TR
+  while IFS=$'' read var; do
+    # section found
+    if [[ $var == \[*\] ]]; then
+      section=$var
+      i=0
+      continue
+    fi
+    # check for valid entry
+    case $var in
+    [0-9]*=1*)
+      case $section in
+      "[Weekplan]")
+        WEEKPLAN[$i]=${var#*|}
+        i=$((i+1))
+        ;;
+      "[Offtimes]")
+        OFFTIMES[$i]=${var#*|}
+        i=$((i+1))
+        ;;
+      "[Events]")
+        EVENTS[$i]=${var#*|}
+        i=$((i+1))
+        ;;
+      "[Macs]")
+        MACS[$i]=$var
+        i=$((i+1))
+        ;;
+      esac
+      # echo "var=$var, sektion=$section, i=$i"
+      ;;
+    esac
+  done < "$INI"
+  rm -f "$INI"
+
+  # read current date, time and day of week
+  DATETIME=`date +%u%Y%m%d%H%M`
+  DOW=${DATETIME:0:1}
+  TODAY=${DATETIME:1:8}
+  CTIME=${DATETIME:9:4}
+
+  ######################################################################
+  # 1) check events
+  for x in ${!EVENTS[@]}; do
+    # 20170130|1100-1200|Layout2|Admin Day
+    str=${EVENTS[$x]}
+    cl_date=${str:0:8}
+    if [ "x$cl_date" = "x$TODAY" ]; then
+      str=${str#*|}
+      cl_time=${str:0:9}
+      cl_time1=${str:0:4}
+      cl_time2=${str:5:4}
+      if [ $CTIME -ge $cl_time1 -a $CTIME -le $cl_time2 ]; then
+        str=${str#*|}
+        cl_layout=${str%|*}
+        cl_note=${str#*|}
+        set_event
+        return
+      fi
+    fi
+  done
+
+  ######################################################################
+  # 2) check offtimes
+  for x in ${!OFFTIMES[@]}; do
+    # YYYYmmdd-YYYYmmdd|Beschreibung
+    str=${OFFTIMES[$x]}
+    cl_date1=${str:0:8}
+    cl_date2=${str:9:8}
+    if [ $TODAY -ge $cl_date1 -a $TODAY -le $cl_date2 ]; then
+      cl_note=${str#*|}
+      set_offtime
+      return
+    fi
+  done
+
+  ######################################################################
+  # 3) check weekplan
+  for x in ${!WEEKPLAN[@]}; do
+    # 5|0730-1230|Layout1
+    str=${WEEKPLAN[$x]}
+    cl_dow=${str:0:1}
+    if [ "x$cl_dow" = "x$DOW" ]; then
+      str=${str#*|}
+      cl_time=${str:0:9}
+      cl_time1=${str:0:4}
+      cl_time2=${str:5:4}
+      if [ $CTIME -ge $cl_time1 -a $CTIME -le $cl_time2 ]; then
+        cl_layout=${str#*|}
+        set_weekplan
+        return
+      fi
+    fi
+  done
+
+  ######################################################################
+  # 4) default, shutdown the screen - when nothing else is todo
+  cl_note="nothing scheduled, shutdown"
+  cl_date1=$TODAY
+  cl_date2=$TODAY
+  set_offtime
+}
+
+# re-check every minute for updating the status.txt
+check_schedule_bgjob() {
+  while :; do
+    # log "check_schedule_bgjob() @ `date`"
+    check_schedule
+    sleep $DSB_SCHEDULE_CHECK
+  done
+}
+
+######################################################################
+# MAIN
+######################################################################
+
+# arrays @ schedule ini
+declare -A "WEEKPLAN" "OFFTIMES" "EVENTS" "MACS"
+
+# init the whole thing
 startup
 
-# globals arrays for the layout
-declare -A "SECTIONS" "TYPES" "LEFT" "TOP" "WIDTH" "HEIGHT" "STYLES"
+# start schedule background job
+check_schedule_bgjob &
 
 # start inotifywait and put in background
 inotifywait --monitor --recursive \
